---
title: "Macaulay PAC Walkathon Fundraiser Summary 2014-2019"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(readxl)
library(janitor)
library(dplyr)
library(tidyr)
library(purrr)
library(fs)
library(stringr)
library(ggplot2)
library(knitr)
library(skimr)
```



```{r peek, eval = FALSE, include = FALSE}
#take a peek at files & derive tidy steps
wat2018 <- read_xlsx("data/WAT Tally 2018.xlsx") %>%
  clean_names() %>% 
  select(teacher, total_counted) %>% 
  drop_na() %>% 
  filter(teacher != "Total") %>% 
  mutate(year = 2018,
         total_counted = as.numeric(total_counted)) 
```


```{r get-data, echo=FALSE}
#filepaths for 2014-2019
wat_files <- dir_ls("data")

#function to read and tidy all files
tidy_wat <- function(filepath){

  fileyear <- str_sub(filepath, 16, 19)
    
    read_excel(filepath) %>% 
    clean_names() %>% 
    select(teacher, total_counted) %>% 
    drop_na() %>% 
    filter(teacher != "Total") %>% 
    mutate(year = fileyear,
           total_counted = as.numeric(total_counted)) 
}

#testing
# filepath <- wat_files[1]
# tidy_wat(filepath)

#map over files, tidy & concatenate into a df
wat_data <- wat_files %>% 
  map_dfr(tidy_wat)

# skim(wat_data)
```

### Total Raised and Number of Participants by Year 2014-2019

```{r summary, echo=FALSE}
totals <- wat_data %>% 
  group_by(year) %>% 
  summarise(total_raised = sum(total_counted),
            number_participants = n()) 
totals %>% 
  kable()
```

### Frequency of Donation Amounts by Year

```{r dist, echo=FALSE}
wat_data %>% 
  group_by(year) %>% 
  ggplot(aes(total_counted)) +
  geom_histogram(aes(y = ..count..), binwidth = 40) +
  facet_wrap(~ year) +
  geom_vline(xintercept = 40, col="blue") +
  theme_minimal() +
  labs(y = "number of kids/sheets",
       x = "amount ($)",
       caption = "vertical blue line indicates $40 mark (t-shirt incentive prize)") 
```


### Class Totals By Year

```{r, echo=FALSE, fig.height=4}
class_totals <- wat_data %>% 
  mutate(teacher = recode(teacher,
                          "LIvernoche" = "Livernoche",
                          "Koch (Turcotte)" = "Koch",
                          "Vally (Leung)" = "Vally")) %>% 
  filter(teacher != "Unknown") %>% 
  group_by(year, teacher) %>%
  summarise(class_total = sum(total_counted))

class_totals %>% 
  ggplot(aes(year, class_total)) +
  geom_point(size = 4) +
  theme_minimal() +
  labs(x = NULL, y = "class total ($)") +
  theme(panel.grid.major.x = element_blank()) +
  scale_y_continuous(limits = c(0, 3000), 
                              breaks = seq(0, 3000, 500), 
                              expand = c(0,0)) +
  geom_hline(yintercept = 2000, col="blue") +
  geom_hline(yintercept = 1500, col="blue")


```

## Number of Classes Raising over $1K by Year

```{r, echo=FALSE}
class_totals %>%
  filter(class_total >= 1000) %>% 
  group_by(year) %>%
  summarise(number = n()) %>% 
  kable(caption = "Number of classes $1K or over")
```


## Number of Prizes Each Year

```{r, echo=FALSE}
prizes <- wat_data %>% 
  mutate(t_shirt = ifelse(total_counted >= 40, 1, 0),
         market_bucks = ifelse(total_counted >= 80, 1, 0),
         rec_centre_pass = ifelse(total_counted >= 125, 1, 0),
         hoodie = ifelse(total_counted >= 175, 1, 0),
         gift_card = ifelse(total_counted >= 250, 1, 0)
  ) %>% 
  pivot_longer(cols = c("t_shirt", "market_bucks", "rec_centre_pass", "hoodie", "gift_card"),
               names_to = "prize",
               values_to = "value") %>% 
  group_by(year, prize) %>% 
  summarise(number = sum(value)) %>% 
  pivot_wider(names_from = prize,
              values_from = number) %>% 
  select(year, t_shirt, market_bucks, rec_centre_pass, hoodie, gift_card)

prizes %>% 
  kable(caption = "Number of Prizes by Type & Year")
  
```


# Number of Particpants Not Earning Prizes by Year
```{r, echo=FALSE}
prizes %>% 
  left_join(totals) %>% 
  select(year, t_shirt, number_participants) %>% 
  mutate(difference = number_participants - t_shirt) %>% 
  kable()
```

